### ISSUE TITLE
Installing 'slapdtest.certs' as data is deprecated

### ISSUE THREAD

**Issue by simevo** [python-ldap/python-ldap#488] opened 2022-08-23 06:43 UTC
## Issue description:

installing python-ldap with pip causes this message to be displayed:

    /tmp/pip-build-env-rnd_tnz8/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning: Installing 'slapdtest.certs' as data is deprecated, please list it in `packages`. 
    !!

    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'slapdtest.certs' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'slapdtest.certs' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'slapdtest.certs' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.

    !!

(the install then continues normally)

## Steps to reproduce: 

```sh
python3 -m venv venv 
source ./venv/bin/activate
pip3 install python-ldap
```

## Operating system: 

Debian 11 stable

## Python version: 

Python 3.9.2

## python-ldap version: 

3.4.2

**Comment by slyngshede** [comment] 2022-08-23 12:47
On macOS the installation doesn't continue, the build simply breaks:
`% python -m pip wheel .                                                                                                                                    14:36:20
Processing /Users/simon/test/python-ldap
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyasn1>=0.3.7
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pyasn1-modules>=0.1.5
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Saved ./pyasn1-0.4.8-py2.py3-none-any.whl
Saved ./pyasn1_modules-0.2.8-py2.py3-none-any.whl
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for python-ldap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.14-arm64-cpython-38
      copying Lib/ldapurl.py -> build/lib.macosx-10.14-arm64-cpython-38
      copying Lib/ldif.py -> build/lib.macosx-10.14-arm64-cpython-38
      creating build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/functions.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/compat.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/ldapobject.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/constants.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/__init__.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/asyncsearch.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/logger.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/resiter.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/modlist.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/dn.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/sasl.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/pkginfo.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/syncrepl.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/filter.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/async.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      copying Lib/ldap/cidict.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap
      creating build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/deref.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/readentry.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/ppolicy.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/sss.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/sessiontrack.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/pwdpolicy.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/openldap.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/pagedresults.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/__init__.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/vlv.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/libldap.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/psearch.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      copying Lib/ldap/controls/simple.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/controls
      creating build/lib.macosx-10.14-arm64-cpython-38/ldap/extop
      copying Lib/ldap/extop/__init__.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/extop
      copying Lib/ldap/extop/passwd.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/extop
      copying Lib/ldap/extop/dds.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/extop
      creating build/lib.macosx-10.14-arm64-cpython-38/ldap/schema
      copying Lib/ldap/schema/subentry.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/schema
      copying Lib/ldap/schema/models.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/schema
      copying Lib/ldap/schema/__init__.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/schema
      copying Lib/ldap/schema/tokenizer.py -> build/lib.macosx-10.14-arm64-cpython-38/ldap/schema
      creating build/lib.macosx-10.14-arm64-cpython-38/slapdtest
      copying Lib/slapdtest/__init__.py -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest
      copying Lib/slapdtest/_slapdtest.py -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest
      running egg_info
      writing Lib/python_ldap.egg-info/PKG-INFO
      writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
      writing requirements to Lib/python_ldap.egg-info/requires.txt
      writing top-level names to Lib/python_ldap.egg-info/top_level.txt
      reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      /private/var/folders/ll/6wc01pzs7n91vxjv0_q567l00000gn/T/pip-build-env-9zur14uk/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      no previously-included directories found matching 'Doc/.build'
      adding license file 'LICENCE'
      writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
      creating build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/README -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/ca.conf -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/ca.pem -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/client.conf -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/client.key -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/client.pem -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/gencerts.sh -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/server.conf -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/server.key -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      copying Lib/slapdtest/certs/server.pem -> build/lib.macosx-10.14-arm64-cpython-38/slapdtest/certs
      running build_ext
      building '_ldap' extension
      creating build/temp.macosx-10.14-arm64-cpython-38
      creating build/temp.macosx-10.14-arm64-cpython-38/Modules
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -DHAVE_SASL -DHAVE_TLS -DLDAPMODULE_VERSION=3.4.2 "-DLDAPMODULE_AUTHOR=python-ldap project" "-DLDAPMODULE_LICENSE=Python style" -IModules -I/Users/simon/test/venv/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -c Modules/LDAPObject.c -o build/temp.macosx-10.14-arm64-cpython-38/Modules/LDAPObject.o
      In file included from Modules/LDAPObject.c:3:
      Modules/common.h:9:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      /private/var/folders/ll/6wc01pzs7n91vxjv0_q567l00000gn/T/pip-build-env-9zur14uk/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'slapdtest.certs' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'slapdtest.certs' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'slapdtest.certs' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'slapdtest.certs' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-ldap
Failed to build python-ldap
ERROR: Failed to build one or more wheels`

I did install python-ldap 3.4.0 three weeks ago in a virtual environment and that worked as expected.

**Comment by tiran** [comment] 2022-08-23 12:51
The warning is unrelated to your build issue on macOS. It's caused by `Modules/common.h:9:10: fatal error: 'Python.h' file not found`

**Comment by slyngshede** [comment] 2022-08-23 12:53
@tiran Ah, yes, I just came to the same conclusion as I was trying to fix the slapdtest.certs.

**Comment by slyngshede** [comment] 2022-08-23 12:58
I created a patch for the original bug: #489

**Comment by droideck** [comment] 2022-08-31 18:12
Fixed by https://github.com/python-ldap/python-ldap/commit/4e53fc927945e294d74cfde1f0e66dee4327637d

**Closed by droideck** 2022-08-31 18:12 UTC
