### ISSUE TITLE
pip install python-ldap failed due to cannot find -lldap_r

### ISSUE THREAD

**Issue by neo-liang-sap** [python-ldap/python-ldap#449] opened 2021-12-14 01:50 UTC
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:

```
Building wheel for python-ldap (PEP 517) ... 25l- \ | / - \ | / - \ error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpehnl6a00
       cwd: /tmp/pip-install-lns9ujs9/python-ldap_21d92058cc1f4f5cafeccf84cd45306c
  Complete output (89 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.9
  copying Lib/ldif.py -> build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.9/ldap
  copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.9/ldap
  creating build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.9/ldap/controls
  copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.9/ldap/controls
  creating build/lib.linux-x86_64-3.9/ldap/extop
  copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.9/ldap/extop
  copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.9/ldap/extop
  copying Lib/ldap/extop/passwd.py -> build/lib.linux-x86_64-3.9/ldap/extop
  creating build/lib.linux-x86_64-3.9/ldap/schema
  copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.9/ldap/schema
  copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.9/ldap/schema
  copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.9/ldap/schema
  copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.9/ldap/schema
  creating build/lib.linux-x86_64-3.9/slapdtest
  copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.9/slapdtest
  copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.9/slapdtest
  running egg_info
  writing Lib/python_ldap.egg-info/PKG-INFO
  writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
  writing requirements to Lib/python_ldap.egg-info/requires.txt
  writing top-level names to Lib/python_ldap.egg-info/top_level.txt
  reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'Doc/.build'
  adding license file 'LICENCE'
  writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.9/slapdtest/certs
  copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.9/slapdtest/certs
  running build_ext
  building '_ldap' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/Modules
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.9/Modules/LDAPObject.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/berval.c -o build/temp.linux-x86_64-3.9/Modules/berval.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/common.c -o build/temp.linux-x86_64-3.9/Modules/common.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/constants.c -o build/temp.linux-x86_64-3.9/Modules/constants.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/functions.c -o build/temp.linux-x86_64-3.9/Modules/functions.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/ldapcontrol.c -o build/temp.linux-x86_64-3.9/Modules/ldapcontrol.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/ldapmodule.c -o build/temp.linux-x86_64-3.9/Modules/ldapmodule.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/message.c -o build/temp.linux-x86_64-3.9/Modules/message.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.4.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/options.c -o build/temp.linux-x86_64-3.9/Modules/options.o
  gcc -shared -Wl,--strip-all build/temp.linux-x86_64-3.9/Modules/LDAPObject.o build/temp.linux-x86_64-3.9/Modules/berval.o build/temp.linux-x86_64-3.9/Modules/common.o build/temp.linux-x86_64-3.9/Modules/constants.o build/temp.linux-x86_64-3.9/Modules/functions.o build/temp.linux-x86_64-3.9/Modules/ldapcontrol.o build/temp.linux-x86_64-3.9/Modules/ldapmodule.o build/temp.linux-x86_64-3.9/Modules/message.o build/temp.linux-x86_64-3.9/Modules/options.o -L/usr/local/lib -lldap_r -llber -o build/lib.linux-x86_64-3.9/_ldap.cpython-39-x86_64-linux-gnu.so
  /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lldap_r
  collect2: error: ld returned 1 exit status
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for python-ldap
```

Steps to reproduce: 

pip install python-ldap

Operating system: 
alpine
Python version: 
3.9
python-ldap version: 
3.3.1 and 3.4.0

**Comment by tiran** [comment] 2021-12-14 08:15
Your bug report is a duplicate of #432 and #445

**Closed by tiran** 2021-12-14 08:15 UTC

**Comment by taoyuanai** [comment] 2022-07-06 09:49
You can try like this before install python-ldap:
**Debian/Ubuntu:**
`sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev`
