### ISSUE TITLE
Installation fails in Python 3.11

### ISSUE THREAD

**Issue by martinfabits** [python-ldap/python-ldap#519] opened 2023-04-13 07:14 UTC
Issue description:
Installation fails in Python 3.11 with the following error:

`      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0`

pip version is 23.0.1
setuptools version is 67.6.1

Steps to reproduce: 
pip3.11 install python-ldap

Operating system: 
RHEL 8.7
Python version: 
3.11.
python-ldap version: 
3.4.3

**Comment by droideck** [comment] 2023-05-29 21:20
I don't think the issue is in python-ldap.

I've tried it on Fedira 38 and it works for me:

```
(env) [spi@ci-vm ~]$ pip3.11 install python-ldap
Collecting python-ldap
  Downloading python-ldap-3.4.3.tar.gz (377 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.4/377.4 kB 9.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyasn1>=0.3.7
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 15.4 MB/s eta 0:00:00
Collecting pyasn1-modules>=0.1.5
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 21.6 MB/s eta 0:00:00
Building wheels for collected packages: python-ldap
  Building wheel for python-ldap (pyproject.toml) ... done
  Created wheel for python-ldap: filename=python_ldap-3.4.3-cp311-cp311-linux_x86_64.whl size=370813 sha256=7d5b0b0305067f160aab0232d3bbb6f73786139259fafc324862a0b35eb4b18d
  Stored in directory: /home/spi/.cache/pip/wheels/68/aa/24/0aa68d59caf381a2b8995c1d69fecda71989be24dcac0ef827
Successfully built python-ldap
Installing collected packages: pyasn1, pyasn1-modules, python-ldap
Successfully installed pyasn1-0.5.0 pyasn1-modules-0.3.0 python-ldap-3.4.3

```

The issue is probably in your local environment, or there's something strange happening with RHEL 8.7 packages or your network access... Either way, I don't think the issue should be fixed on our side.

**Closed by droideck** 2023-05-29 21:20 UTC
