### ISSUE TITLE
Fails to build with OpenLDAP 2.5+ – libldap_r has been merged into libldap

### ISSUE THREAD

**Issue by jirutka** [python-ldap/python-ldap#438] opened 2021-11-02 18:41 UTC
```
gcc -shared -Wl,--as-needed,-O1,--sort-common -fno-semantic-interposition -Wl,--as-needed,-O1,--sort-common -fno-semantic-interposition -Wl,--as-needed,-O1,--sort-common -Os -fomit-frame-pointer -Os -fomit-frame-pointer build/temp.linux-x86_64-3.9/Modules/LDAPObject.o build/temp.linux-x86_64-3.9/Modules/berval.o build/temp.linux-x86_64-3.9/Modules/common.o build/temp.linux-x86_64-3.9/Modules/constants.o build/temp.linux-x86_64-3.9/Modules/functions.o build/temp.linux-x86_64-3.9/Modules/ldapcontrol.o build/temp.linux-x86_64-3.9/Modules/ldapmodule.o build/temp.linux-x86_64-3.9/Modules/message.o build/temp.linux-x86_64-3.9/Modules/options.o -L/usr/lib -lldap_r -llber -o build/lib.linux-x86_64-3.9/_ldap.cpython-39-x86_64-linux-musl.so
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lldap_r
collect2: error: ld returned 1 exit status
error: command '/usr/bin/gcc' failed with exit code 1
```

[OpenLDAP 2.5 Announcement](https://lists.openldap.org/hyperkitty/list/openldap-announce@openldap.org/thread/BH3VDPG6IYYF5L5U6LZGHHKMJY5HFA3L/):

> libldap_r has been merged with libldap

**Comment by kernighan** [comment] 2021-11-02 18:45
This is a duplicate of #432

**Comment by tiran** [comment] 2021-11-02 18:45
Closing this as duplicate of #432

**Closed by tiran** 2021-11-02 18:45 UTC

**Comment by jirutka** [comment] 2021-11-02 18:50
Ah, sorry, I had to mistype the query or something cause I’ve been trying to find existing issues for this problem and found none.
